apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: frog-docs-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: frog-docs
  updatePolicy:
    updateMode: "Auto"
